build:
    build_starting:
        image: python:2
        commands:
            - echo "Beginning new build"
    run_tests:
        image: python:2-alpine
        commands:
            - pip install -r requirements.txt
            - python testing.py
publish:
    docker:
        repo: stubryan/cicd_demoapp
        tag: latest
        username: stubryan
        password: Sixbells6
        email: stubryan@cisco.com
deploy:
    webhook:
        image: plugins/drone-webhook
        skip_verify: true
        method: POST
        auth:
            username: admin
            password: 1vtG@lw@y
        urls:
            - https://mantlsandbox.cisco.com/marathon/v2/apps/class/stubryan/restart?force=true
notify:
    spark:
        image: hpreston/drone-spark
        auth_token: YTE5ZDZjYzAtMmM5ZC00YTViLWI0MjYtNTNhNDI1ZGJhYjJlZWIyNDlkNTctYmYx
        roomId: Y2lzY29zcGFyazovL3VzL1JPT00vODU2MDlkMzAtZTE1NS0xMWU2LTg3YTQtMzlhMGRlZDgwNzhk
