build:
    build_starting:
        image: python:2
        commands:
            - echo "Beginning new build"
    run_tests:
        image: python:2-alpine
        commands:
            - pip install -r requirements.txt
            - python testing.py
publish:
    docker:
        repo: stubryan/cicd_demoapp
        tag: latest
        username: stubryan
        password: Sixbells6
        email: stubryan@cisco.com
deploy:
    webhook:
        image: plugins/drone-webhook
        skip_verify: true
        method: POST
        auth:
            username: admin
            password: 1vtG@lw@y
        urls:
            - https://mantlsandbox.cisco.com/marathon/v2/apps/class/stubryan/restart?force=true
